---
title: "Untitled"
author: "Daniel Sabater"
date: "2022-09-28"
output: html_document
---


```{r setup, include=FALSE}
#We are going to load the packages required for the project
options(scipen=999)
library(tidyverse) #Data manipulation
library(lubridate)
library(readr)
library(RColorBrewer)#Palette of colors
library(qqplotr) # for qqplot
library(ggpubr) #for merge plots

#For extreme value estimation of parameters. It uses 
#MLE, this estimation can have some problems with
#estimation in small samples.
library(evd)
library(rBayesianOptimization)
library(kdensity)

library(xtable) #Used 
library(extRemes) #For fit GP



#To extract the colors of Rbrewer
#f <- function(pal) brewer.pal(brewer.pal.info[pal, "maxcolors"], pal)
#(cols <- f("Set2"))


cols <- c("Inundacion"= "#E78AC3",
          "Tormenta" = "#FFD92F",
          "Terremoto"="#8DA0CB",
          "Ciclon" = "#FC8D62",
          "Incendio_Forestal"="#66C2A5",
          "Granizada" = "#A6D854",
          "Tornado" = "#E5C494")

##Alternatives
#evir, extRemes, fExtremes, and POT 

#fExtremes allow employ Probability 
#Weighted Moments method. It can
#be  useful for small smaples

setwd("C:/Users/saac9/OneDrive - Universidad de Costa Rica/Documents/UCR/2022/Distribuciones_de_Perdidas/Proyecto_Dist_Per")
base_de_datos <- read_csv("base_de_datos.csv")
base_de_datos<-base_de_datos %>%select(-c(`REGION / TOWN`,FinYeae ))
base_de_datos<-base_de_datos[-c(12:length(base_de_datos))]

base_de_datos<-base_de_datos[!(is.na(base_de_datos$Type)|base_de_datos$Type=="Other"|base_de_datos$Type=="East Coast Low"|base_de_datos$Type=="Wind"),]

base_de_datos$`CAT EVENT START`<-as.Date(base_de_datos$`CAT EVENT START`, "%m/%d/%y")
base_de_datos$`CAT EVENT FINISH`<-as.Date(base_de_datos$`CAT EVENT FINISH`, "%m/%d/%y")

base_de_datos$Type<-as.factor(base_de_datos$Type)

base_de_datos$YEAR<-as.numeric(base_de_datos$YEAR)
base_de_datos$`ORIGINAL LOSS VALUE`<-as.numeric(base_de_datos$`ORIGINAL LOSS VALUE`)
base_de_datos$`NORMALISED LOSS VALUE (2017)`<-as.numeric(base_de_datos$`NORMALISED LOSS VALUE (2017)`)



base_de_datos$Type<-recode_factor(base_de_datos$Type, "Bushfire"="Incendio forestal",
                                  "Cyclone" = "Ciclón", "Earthquake"="Terremoto",
                                  "Flooding"="Inundación",  "Hailstorm" ="Granizada", 
                                  "Storm"="Tormenta" )


base_de_datos$`NORMALISED LOSS VALUE (2017)`[is.na(base_de_datos$`NORMALISED LOSS VALUE (2017)`) ]<-0

base_de_datos<-base_de_datos[base_de_datos$`NORMALISED LOSS VALUE (2017)`>1,]


```


```{r, fig.align="center",fig.width=11, fig.height=7, echo=FALSE, message=FALSE, warning=FALSE,fig.cap='titulo'}
CantidadPorAno <-
  as.data.frame(base_de_datos %>% group_by(Type) %>% count(YEAR))

imagen1<-CantidadPorAno %>% ggplot(aes(
  x = YEAR,
  y = n,
  group = Type,
  color = Type
)) +
  geom_line(size = 1.25) +
  scale_color_discrete(name = "Tipo") +
  facet_wrap( ~ Type,
              ncol = 2,
              dir = "v",
              scales = "free_y" ) +
  labs(y = "Cantidad", x = "Año") +
  scale_x_continuous(breaks = seq(min(CantidadPorAno$YEAR), max(CantidadPorAno$YEAR), 5),
                     minor_breaks = seq(0, 16, 1), ) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  theme_minimal() +
  theme(
    text =  element_text(size = 17),
    legend.position = "none",
    plot.caption = element_text(hjust = 0),
    axis.text.x = element_text(angle = 25),
    panel.spacing = unit(0.65, "cm"),
    strip.text = element_text(size = 17)
  )
imagen1
ggsave(file="CantidadporAno.pdf", plot=imagen1, width=11, height=7)

```

```{r, fig.align="center",fig.width=11, fig.height=7, echo=FALSE, message=FALSE, warning=FALSE,fig.cap='titulo'}
names(CantidadPorAno)<-c("Tipo","año","cantidad")
cantidad_de_años_con_la_misma_cantidad_de_tornados<-as.data.frame(CantidadPorAno%>% group_by(Tipo) %>% count(cantidad))

#Frecuencia del numero de eventos por año

imagen1<-cantidad_de_años_con_la_misma_cantidad_de_tornados%>%ggplot(aes(x=cantidad, y = n,group=Tipo, color=Tipo, fill=Tipo))+
  geom_bar(
    stat = "identity",
    width = 0.75,
    position = position_dodge2(width = 20, preserve = "single")
  ) +
  scale_x_continuous(breaks = seq(0, 16, 1),
                     minor_breaks = seq(0, 16, 1)) +
  scale_y_continuous(breaks = seq(
    0,
    length(cantidad_de_años_con_la_misma_cantidad_de_tornados$n),
    2
  ),
  minor_breaks = seq(
    0,
    length(cantidad_de_años_con_la_misma_cantidad_de_tornados$n),
    1
  )) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  labs(x = "Número de eventos", y = "Frecuencia a través de los años") +
  guides(color = guide_legend(title = "Tipo de evento"),
         fill = guide_legend("Tipo de evento")) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    plot.caption = element_text(hjust = 0),
    text =  element_text(size = 16)
  )

imagen1
ggsave(file="FrecuencPorAno.pdf", plot=imagen1, width=11, height=7)
```
 


```{r, fig.align="center",fig.width=11, fig.height=7, echo=FALSE, message=FALSE, warning=FALSE,fig.cap='titulo'}
imagen1<-base_de_datos%>%ggplot(aes(y = Type, x = `NORMALISED LOSS VALUE (2017)`/1000000, group=Type, color=Type)) +
  geom_boxplot(aes(color = Type), alpha = 1) +
  stat_boxplot(geom='errorbar', linetype=1, width=0.5)+
  geom_jitter(aes(color = Type), size = 1, alpha = 0.09)+
  scale_color_discrete(name = "Type")+
  stat_summary(fun.y=mean, geom="point", shape=18,size=3)+
  #facet_wrap(~ Type,ncol = 2,dir = "v",scales = "free" )+
  scale_x_continuous(breaks=seq(0, max(base_de_datos$`NORMALISED LOSS VALUE (2017)`, na.rm = T)/1000000, 1000/2))+
  scale_fill_brewer(palette="Set2")+
  scale_color_brewer(palette="Set2")+
  labs( y='',x='Montos de perdidas (en millones de dólares australianos)')+
  guides(color=guide_legend(title="Tipo de evento"),fill=guide_legend("Tipo de evento")) +
  theme_minimal()+
  theme(
        legend.position="none",
        plot.caption = element_text(hjust = 0),
        text =  element_text(size=17))
imagen1
ggsave(file="PerdidasConjunta.pdf", plot=imagen1, width=11, height=7)
```



```{r, fig.align="center",fig.width=11, fig.height=7, echo=FALSE, message=FALSE, warning=FALSE,fig.cap='titulo'}
imagen1<-base_de_datos %>% ggplot(aes(
  y = Type,
  x = `NORMALISED LOSS VALUE (2017)` / 1000000,
  group = Type,
  color = Type
)) +
  geom_boxplot(aes(color = Type), alpha = 1) +
  stat_boxplot(geom = 'errorbar',
               linetype = 1,
               width = 0.5) +
  geom_jitter(aes(color = Type), size = 1, alpha = 0.09) +
  scale_color_discrete(name = "Type") +
  stat_summary(
    fun.y = mean,
    geom = "point",
    shape = 18,
    size = 3
  ) +
  facet_wrap( ~ Type,
              #ncol = 2,
              #dir = "v",
              scales = "free") +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  scale_x_continuous(n.breaks = 6) +
  labs(y = '', x = 'Montos de perdidas (en millones de dólares australianos)') +
  theme_minimal() +
  theme(
    axis.text.y = element_blank(),
    legend.position = "none",
    plot.caption = element_text(hjust = 0),
    text =  element_text(size = 17),
    strip.text = element_text(size = 17),
    panel.spacing = unit(0.75, "cm")
  )
imagen1
ggsave(file="PerdidasIndividuales.pdf", plot=imagen1, width=11, height=7)
```



```{r, fig.align="center",fig.width=11, fig.height=7, echo=FALSE, message=FALSE, warning=FALSE,fig.cap='titulo'}
imagen1<-base_de_datos %>% ggplot(aes(
  x = `NORMALISED LOSS VALUE (2017)` / 1000000,
  group = Type,
  color = Type,
  fill = Type)) +
  #geom_density(alpha = 0.7) +
  geom_histogram()+
  scale_x_continuous(n.breaks = 6) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Set2") +
  facet_wrap( ~ Type
              #, scales = "free"
              ) +
  labs(x = "Montos de perdidas (en millones de dólares australianos)", y = "Frecuencia") +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.caption = element_text(hjust = 0.5),
    text =  element_text(size = 17),
    strip.text = element_text(size = 17),
    panel.spacing = unit(0.75, "cm")
  )
imagen1
ggsave(file="PerdidasHistrograma.pdf", plot=imagen1, width=11, height=7)
```




































## Model employing Machine Learning
```{r}
#Estimation function by kernel density
#We create a function that estimate de parameteres
#employing MLE and POT method
#X is the data
#u is the threshold
#x is the parameter that wants to be
#estimated

events <- unique(base_de_datos$Type)


mean_excess_plot <- function(X,cols="red",title){
  X <- sort(X/1000000)
  #print(rango)
  u <- seq(min(X),X[length(X)-1], length.out=1000)
  fn <- function(u){
    return(mean((X[X>u]-u)))
  }
  mean_excess <- unlist(lapply(u, FUN=fn))
  plot <- ggplot(,)+geom_line(aes(x=u,y=mean_excess),colour=cols,size=2) + theme(
                  text =  element_text(size = 17),
                  legend.position = "none",
                  plot.caption = element_text(hjust = 0),
                  panel.spacing = unit(0.65, "cm"),
                  strip.text = element_text(size = 17),
                  axis.text.x = element_text(angle = 25),
                  plot.title = element_text(hjust = 0.5),
                ) + ggtitle(title
                ) + xlab("Umbral (en millones de dolares autralianos)"
                ) + ylab("Media sobre el exceso")
  return(plot)
}


GPD_MLE <- function(X,u){
  model <- extRemes::fevd(X,threshold = u,type="GP") #evd::fpot(x=X,threshold = u, model = "gpd",std.err=FALSE) #Fit the parameters
  results <- summary(model)
  scale <- results$par[1]
  shape <- results$par[2]
  AIC <- results$AIC
  BIC <- results$BIC
  return(c(shape,scale,AIC,BIC)) #We return the value
}


#summary(prueba) <- extRemes::fevd(c(1,2,3,5,56,6547,578,567),threshold = 5,type="GP")
#prueba2$AIC <- summary(prueba)

norm_L_1_GPD_KDE <- function(X,eps=0,iter=1000,lower,upper){
  lower <- lower/1000000
  upper <- upper/1000000
  
  Y <- X/1000000

  fn <- function(u){
    kde <- kdensity(Y[Y>u]-u,kernel="gaussian",normalized=FALSE)
    GPD_params <- GPD_MLE(Y,u)
    F_kde_u <-  integrate(function(x) kde(x-eps),lower=eps,upper = Inf)$value
    integral <- integrate(function(x) abs(kde(x)/(F_kde_u)-extRemes::devd(x-u,loc=0,scale=GPD_params[2],shape= GPD_params[1],type="GP",log=FALSE)),lower = 0,upper=Inf)$value
  
    return(integral)
    
  }
  #return(BayesianOptimization(FUN=fn,bounds = list(u=c(m,M)),n_iter=iter))
  optim(par=lower,fn,lower=lower,upper=upper, method="Brent")
  
}




parameters <- function(X,eps=0,iter=1000,lower,upper){
  p <- norm_L_1_GPD_KDE(X,eps=eps,iter=iter,lower=lower,upper = upper)
  GPD_params <- GPD_MLE(X,u=p$par*1000000)
  return(list(shape=GPD_params[1],scale=GPD_params[2],AIC=GPD_params[3],BIC=GPD_params[4],u=p$par*1000000,error=p$value))
}




create_qqplot <- function(data,distribution,list_params,cols="red",title){
        plot <- ggplot(,)+stat_qq_line(aes(sample=data),distribution = distribution, dparams= list_params,colour=cols,size=2) + stat_qq_point(aes(sample=data),distribution = distribution, dparams = list_params)+theme(
                  text =  element_text(size = 17),
                  legend.position = "none",
                  plot.caption = element_text(hjust = 0),
                  panel.spacing = unit(0.65, "cm"),
                  strip.text = element_text(size = 17),
                  plot.title = element_text(hjust = 0.5),
                  axis.text.x = element_text(angle = 25),
                ) + ggtitle(title
                ) + xlab("Teórico"
                ) + ylab("Muestral"
                ) + scale_x_continuous(labels = round(seq(0,max(data)/1000,length.out = 4 ),0),breaks = seq(0,max(data),length.out = 4 ))

        return(plot)
}

create_ppplot <- function(data,distribution,list_params){
        plot <- ggplot(,)+stat_pp_line(aes(sample=data)) + stat_pp_point(aes(sample=data))
        return(plot)
}

create_dplot <- function(X,list_params,cols="red",title,u){
        M <-max(X)
        X<-X[X > u]-u
        #counting <- as.data.frame(table(X))
        #counting$Freq <- as.numeric(counting$Freq)
        #counting$X <- as.numeric(counting$X)
        #number <- as.numeric(names(counting)[-1])
        #print(counting)
        #print(number)

        plot<- ggplot(,)+ scale_x_continuous(breaks = seq(0,M,length.out=4),labels = round(seq(0,M/1000,length.out=4),0),limits=c(0,M)) +stat_function(size=2,fun = extRemes::devd,args=list(shape=list_params$shape,loc=list_params$loc,scale=list_params$scale),colour=cols)+theme(
                text =  element_text(size = 17),
                legend.position = "none",
                plot.caption = element_text(hjust = 0),
                panel.spacing = unit(0.65, "cm"),
                strip.text = element_text(size = 17),
                axis.text.x = element_text(angle = 25),
                plot.title = element_text(hjust = 0.5)
              )   + ggtitle(title
                ) + xlab('Montos (en dólares australianos)'
                ) + ylab("Densidad"
                ) 
        return(plot)
}



#We are going to generate the plot to analize where could be u
for (i in 1:length(events)){
  X <- t(base_de_datos%>%filter(Type == events[i])%>%select(`NORMALISED LOSS VALUE (2017)`))
  X[is.na(X)]<-0
  assign(paste("mean_excess_plot",events[i],sep="_"),mean_excess_plot(X = X,cols = cols[i],title=events[i]))
}



max_events <- numeric()
#Max of each event 
for (i in 1:length(events)){
  X <- (base_de_datos%>%filter(Type == events[i])%>%select(`NORMALISED LOSS VALUE (2017)`))
  max_events[i] <- max(X,na.rm=TRUE)
}


vector_events <- c("inundacion","tormenta","terremoto","ciclon","incendio_forestal","granizada","tornado")
for (i in 1:length(events)){
  X <- (base_de_datos%>%filter(Type == events[i])%>%select(`NORMALISED LOSS VALUE (2017)`))
  X <- max(X[X<max_events[i]]-1000)/max_events[i]
  assign(paste("upper",vector_events[i],sep="_"),X)
}


million <- 1000000
lower_upper_incendio_forestal <- c(125*million,250*million) 
lower_upper_ciclon <- c(500*million,750*million)
lower_upper_terremoto <- c(25*million,65*million)
lower_upper_inundacion <- c(250*1000000,750*1000000)
lower_upper_granizada <- c(300*million,550*million)
lower_upper_tormenta <- c(250*million,450*million)
lower_upper_tornado <- c(7*million,11*million)



#We are going to estimate the parameters for the model
estimation_nakamura <- data.frame("Evento"=character(),"Mínimo"=numeric(),"Máximo"=numeric(),shape = numeric(),scale=numeric(),AIC = numeric(),BIC=numeric(),u=numeric(),error=numeric())


for (i in 1:length(events)){
  data_model <- base_de_datos%>%filter(Type == events[i])
  X <- t(data_model%>%select(`NORMALISED LOSS VALUE (2017)`))
  X[is.na(X)] <- 0 
  #print(length(X))
  lower_upper_graph <- get(paste("lower_upper",vector_events[i],sep="_")) #Lower and higher obtained from analyisis
  #print(X)
  estimation <- parameters(X,lower=lower_upper_graph[1],upper=lower_upper_graph[2])
  estimation_nakamura <- rbind(estimation_nakamura, data.frame("Evento"=events[i],"Mínimo"=lower_upper_graph[1],"Máximo"=lower_upper_graph[2],shape = estimation$shape,scale=estimation$scale,AIC=estimation$AIC,BIC=estimation$BIC,u=estimation$u,error=estimation$error))
}


#We are going to create plots qqplot and pplot

for (i in 1:length(events)){
  X <- t(base_de_datos%>%filter(Type == events[i])%>%select(`NORMALISED LOSS VALUE (2017)`))
  X[is.na(X)]<-0
  X<- X[X>estimation_nakamura$u[i]]-estimation_nakamura$u[i]
  assign(paste("qq_plot",events[i],sep="_"),create_qqplot(title=events[i],cols=cols[i], data=X,distribution="evd",list_params=list(shape=estimation_nakamura$shape[i],scale = estimation_nakamura$scale[i],loc = 0,type="GP")))
}
qq_plot_Ciclón

for (i in 1:length(events)){
  X <- t(base_de_datos%>%filter(Type == events[i])%>%select(`NORMALISED LOSS VALUE (2017)`))
  X[is.na(X)]<-0
  X<- X[X>estimation_nakamura$u[i]]
  assign(paste("pp_plot",events[i],sep="_"),create_ppplot(data=X,distribution="gpd",list_params=list(shape=estimation_nakamura$shape[i],scale = estimation_nakamura$scale[i],loc = estimation_nakamura$u[i],color=cols[i])))
}

#We create the density plot
for (i in 1:length(events)){
  X <- t(base_de_datos%>%filter(Type == events[i])%>%select(`NORMALISED LOSS VALUE (2017)`))
  X[is.na(X)]<-0
  assign(paste("density_plot",events[i],sep="_"),create_dplot(u=estimation_nakamura$u[i],title=events[i],cols=cols[i],X=X,list_params=list(shape=estimation_nakamura$shape[i],scale = estimation_nakamura$scale[i],loc = 0,type="GP")))
}
density_plot_Tormenta



#We join the plots 
densities_plot <-ggarrange(`density_plot_Incendio forestal`+theme_minimal(),
                  density_plot_Ciclón+theme_minimal(),
                  density_plot_Terremoto+theme_minimal(),
                  density_plot_Inundación+theme_minimal(),
                  density_plot_Granizada+theme_minimal(),
                  density_plot_Tormenta+theme_minimal(),
                  density_plot_Tornado+theme_minimal(),
                  ncol=3,
                  nrow = 3)
densities_plot



qq_plots <-ggarrange(`qq_plot_Incendio forestal`+theme_minimal(),
                  qq_plot_Ciclón+theme_minimal(),
                  qq_plot_Terremoto+theme_minimal(),
                  qq_plot_Inundación+theme_minimal(),
                  qq_plot_Granizada+theme_minimal(),
                  qq_plot_Tormenta+theme_minimal(),
                  qq_plot_Tornado+theme_minimal(),
                  ncol=3,
                  nrow = 3)
qq_plots


mean_excess_plots <-ggarrange(`mean_excess_plot_Incendio forestal`+theme_minimal(),
                  mean_excess_plot_Ciclón+theme_minimal(),
                  mean_excess_plot_Terremoto+theme_minimal(),
                  mean_excess_plot_Inundación+theme_minimal(),
                  mean_excess_plot_Granizada+theme_minimal(),
                  mean_excess_plot_Tormenta+theme_minimal(),
                  mean_excess_plot_Tornado+theme_minimal(),
                  ncol=3,
                  nrow = 3)
mean_excess_plots

#We save the plots
ggsave("densities_method_nakamura.pdf",plot=densities_plot, width=11, height=7)
ggsave("qqplot_method_nakamura.pdf",plot=qq_plots, width=11, height=7)
ggsave("mean_excess_plots.pdf",plot=mean_excess_plots, width=11, height=7)

#We create a table with estimated values
print(xtable(estimation_nakamura, type = "latex", tabular.environment="longtable"),
    include.rownames=FALSE, file = "estimation_nakamura.tex")

```























